import type { Metadata } from "next";
import "./styles/app.scss";
import "./styles/header.scss";
import "./styles/footer.scss";
import "./styles/home.scss";
import "./styles/market.scss";
import "./styles/winninganimation.scss";
import "./styles/profile.scss";
import "./styles/modals.scss";
import "./styles/exploredetail.scss";
import { ToastContainer } from "react-toastify";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar
          toastClassName="custom-toast"
        />
      </body>
    </html>
  );
}
