name: Deploying stage Branch

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: [self-hosted, speed-market-dev-vm]

    env:
      PM2_PROCESS_NAME: Speed-Market-Stg-FE
      PORT: 3001
      node-version: 22

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false
          path: staging

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: staging

      - name: Create build
        run: npm run build
        working-directory: staging

      - name: Start or Reload the Application
        run: |
          if pm2 list | grep -q "$PM2_PROCESS_NAME"; then
            echo "Process $PM2_PROCESS_NAME exists. Reloading..."
            pm2 reload "$PM2_PROCESS_NAME"
          else
            echo "Process $PM2_PROCESS_NAME does not exist. Starting..."
            PORT=$PORT pm2 start "npm start" --name "$PM2_PROCESS_NAME"
          fi
          pm2 save
        working-directory: staging
